services:
  - type: web
    name: pneumonia-detection
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT "Flask Application.app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
